/*
 PROFORMAS
 */
package paneles;
import Controlador.ConcesionarioDAO;
import Controlador.Conexion;
import Controlador.MotoDAO;
import Controlador.ProformaDAO;
import Controlador.ProformaDetalleDAO;
import Modelo.Concesionario;
import Modelo.Detalle_Proforma;
import Modelo.Moto;
import Modelo.Proforma;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.lang3.math.NumberUtils;
import static paneles.pnlPedidos.ParseFecha;
/**
 *
 * @author RojeruSan
 */
public class pnlProformas extends javax.swing.JPanel {

    Detalle_Proforma detpro=new Detalle_Proforma();
    ProformaDetalleDAO detprodao=new ProformaDetalleDAO();
    Proforma pro=new Proforma();
    ProformaDAO prodao=new ProformaDAO();
    Concesionario conc=new Concesionario();
    ConcesionarioDAO concdao=new ConcesionarioDAO();
    Moto moto=new Moto();
    MotoDAO motodao= new MotoDAO();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    
    public pnlProformas() {
        initComponents();
        mostrarListaMotos();
        ListaComboConcecionario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblErrorLetra2 = new javax.swing.JLabel();
        ComboBoxConcesionario = new javax.swing.JComboBox<String>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaMotos = new javax.swing.JList<String>();
        jLabel18 = new javax.swing.JLabel();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLSubtotal = new javax.swing.JLabel();
        jLIVA = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLTotal = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtColor = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblErrorLetra = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/feeedback.png"))); // NOI18N
        jLabel7.setText("PROFORMAS");

        jButton2.setText("Borrar Campos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("Código Proforma");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setText("Fecha");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("Concesionario");

        ListaMotos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ListaMotos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ListaMotosKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(ListaMotos);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setText("Motos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblErrorLetra2)
                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(ComboBoxConcesionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(ComboBoxConcesionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorLetra2))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Subtotal:");

        jLSubtotal.setText("Subtotal");

        jLIVA.setText("IVA");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("IVA:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("Total:");

        jLTotal.setText("Total");

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColorKeyTyped(evt);
            }
        });

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setText("Color");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel20.setText("Cantidad");

        lblErrorLetra.setForeground(new java.awt.Color(255, 51, 0));

        jButton4.setText("Imprimir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(136, 136, 136))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(169, 169, 169)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLIVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(177, 177, 177))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lblErrorLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLSubtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLIVA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLTotal))
                .addGap(63, 63, 63)
                .addComponent(lblErrorLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
txtId.setText("");
txtColor.setText("");
txtCantidad.setText("");
ComboBoxConcesionario.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try
        {
            setDatos();setDatosDetalle();
        costo("");
        prodao.registrarProforma(pro);
        detprodao.registrarDetalleProforma(detpro);
        int i=0;
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "ERROR "+ e.getMessage());
        }
         
        
        
        
        
        //mostrarDatos("");
        //reset();        
    }//GEN-LAST:event_btnAgregarActionPerformed
void costo(String valor){
        //JOptionPane.showMessageDialog(null, ComboBoxConcesionario.getSelectedItem());
        Conexion con = new Conexion();       
        String sql="";   
        valor=ListaMotos.getSelectedValue();
//tblMotos.setModel(modelo1);
        float aux=0,to=0;
        sql="SELECT moto.precio FROM `moto` WHERE id_moto="+"'"+valor+"'";          
        String []datos = new String[8];
        try{
            Statement st = con.getConnection().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                
                
            }
            to=Float.parseFloat(datos[0])*Float.parseFloat(txtCantidad.getText());
            jLSubtotal.setText(to+"");
            aux=(float) (to*0.12);
            jLIVA.setText(aux+"");
            aux=(float) (to+aux);;
            jLTotal.setText(aux+"");
            //jfmotoadmin.tblMotos.setModel(modelo1);
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, txtFecha.getDate());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
int k=(int)evt.getKeyChar();
if (k >= 97 && k <= 122 || k>=65 && k<=90){
evt.setKeyChar((char)KeyEvent.VK_CLEAR);
lblErrorLetra.setText("Ingresa Solo Números");
}
if(k==241 || k==209){
evt.setKeyChar((char)KeyEvent.VK_CLEAR);
lblErrorLetra.setText("Ingresa Solo Números");
}
if(k==10){
txtId.transferFocus();}           // TODO add your handling code here:
    }//GEN-LAST:event_txtIdKeyTyped

    private void ListaMotosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ListaMotosKeyTyped
char c=evt.getKeyChar();

        if(Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
            lblErrorLetra.setText("Ingresa Solo Letras");

        }         // TODO add your handling code here:
    }//GEN-LAST:event_ListaMotosKeyTyped

    private void txtColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorKeyTyped
        char c=evt.getKeyChar();

        if(Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
            lblErrorLetra.setText("Ingresa Solo Letras");

        }         // TODO add your handling code here:
    }//GEN-LAST:event_txtColorKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
     int k=(int)evt.getKeyChar();
if (k >= 97 && k <= 122 || k>=65 && k<=90){
evt.setKeyChar((char)KeyEvent.VK_CLEAR);
lblErrorLetra.setText("Ingresa Solo Números");
}
if(k==241 || k==209){
evt.setKeyChar((char)KeyEvent.VK_CLEAR);
lblErrorLetra.setText("Ingresa Solo Números");
}
if(k==10){
txtCantidad.transferFocus();}    // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            try {
            crearPDF("PRO"+txtId.getText(),sdf.format(txtFecha.getDate()),ComboBoxConcesionario.getSelectedItem()+"",jLSubtotal.getText(),jLIVA.getText(),jLTotal.getText(),txtColor.getText(),txtCantidad.getText(),ListaMotos.getSelectedValue());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(pnlProformas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(pnlProformas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
   private boolean validarCamposVacios() {
        return txtId.getText().isEmpty() || txtFecha.getDate() == null ;
    }
public void ListaComboConcecionario()
    {
        Conexion con = new Conexion();       
        String sql="SELECT id_concesionario FROM concesionario";
        //String []datos = new String[10];;   
        try{
            Statement st = con.getConnection().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                ComboBoxConcesionario.addItem(rs.getString(1));
                               
            }
            //jfmotoadmin.tblMotos.setModel(modelo1);
        }catch(SQLException e){
            System.out.println(e);
        }
    }
    public void mostrarListaMotos()
    {
        Conexion con = new Conexion();       
        int i=0;
        String sql="SELECT id_moto FROM moto";
        String []datos = new String[10];  
        ArrayList<String> motos = new ArrayList<String>();
        try{
            Statement st = con.getConnection().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                motos.add(rs.getString(1));
                datos[i++]=rs.getString(1);
                              
            }
            ListaMotos.setListData(datos);
            //jfmotoadmin.tblMotos.setModel(modelo1);
        }catch(SQLException e){
            System.out.println(e);
        }
        
    }
    public void setDatos() // obtiene los datos de la moto cuando se selecciona una
    {
        try{
            
            //fecha=SimpleDateFormat.parse();

                String Fecha = sdf.format(txtFecha.getDate());
            pro.setId_proforma("PRO"+txtId.getText());
            //pro.setEstado(txtEstado.getText());
            pro.setFecha_recepcion(ParseFecha(Fecha));
            pro.setTotal(20);
            pro.setIdConcesionario(ComboBoxConcesionario.getSelectedItem()+"");
       //pro.setDetalle(txtEstado.getText());
       //pro.set(txtTelefono.getText());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void setDatosDetalle() // obtiene los datos de la moto cuando se selecciona una
    {
        try{
            detpro.setIdDetalleProforma("1");
            detpro.setIdProforma("PRO"+txtId.getText());
            detpro.setIdmoto(ListaMotos.getSelectedValue());
            detpro.setCantidad(Integer.parseInt(txtCantidad.getText()));
            detpro.setColor(txtColor.getText());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public static Date ParseFecha(String fecha)
    {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaDate = null;
        try {
            fechaDate = formato.parse(fecha);
        } 
        catch (ParseException ex) 
        {
            System.out.println(ex);
        }
        return fechaDate;
    }
    
     public static void crearPDF(String txtId,String txtFecha,String txtConce, String Subtotal, String IVA, String Total,String color,String Cantidad, String moto) throws FileNotFoundException, DocumentException {
        // Se crea el documento
        Document documento = new Document();
        try{
        // El OutPutStream para el fichero donde crearemos el PDF
        FileOutputStream ficheroPDF = new FileOutputStream("Proforma.pdf");
        
        // Se asocia el documento de OutPutStream
        PdfWriter.getInstance(documento, ficheroPDF);
        
        // Se abre el documento
        documento.open();
        
        // Parrafo
        Paragraph titulo = new Paragraph("Proforma Motos S.A \n\n",
                FontFactory.getFont("arial",
                        24,
                        Font.BOLD,
                        BaseColor.BLUE
                        )
        );
        
         Paragraph cabeza = new Paragraph("Cod_Proforma: "+txtId+"\n",
                FontFactory.getFont("arial",
                        15,
                        Font.PLAIN,
                        BaseColor.BLACK
                        )
        );
         Paragraph cabeza2 = new Paragraph("Fecha: "+txtFecha+"\n",
                FontFactory.getFont("arial",
                        15,
                        Font.PLAIN,
                        BaseColor.BLACK
                        )
        );
         Paragraph cabeza3 = new Paragraph("Concesionario: "+txtConce+"\n\n\n",
                FontFactory.getFont("arial",
                        15,
                        Font.PLAIN,
                        BaseColor.BLACK
                        )
        );
         
         Paragraph Pie = new Paragraph("\n\n\nSubtotal:\n",
                FontFactory.getFont("arial",
                        12,
                        Font.BOLD,
                        BaseColor.BLACK
                        )
        );
                  Paragraph Valor= new Paragraph(Subtotal,
                FontFactory.getFont("arial",
                        12,
                        Font.PLAIN,
                        BaseColor.BLACK
                        )
        );
                  Paragraph Pie2 = new Paragraph("\nIVA:\n",
                FontFactory.getFont("arial",
                        12,
                        Font.BOLD,
                        BaseColor.BLACK
                        )
        );
                   Paragraph Valor2= new Paragraph(IVA,
                FontFactory.getFont("arial",
                        12,
                        Font.PLAIN,
                        BaseColor.BLACK
                        )
        );
                           Paragraph Pie3 = new Paragraph("\nTotal:\n",
                FontFactory.getFont("arial",
                        12,
                        Font.BOLD,
                        BaseColor.BLACK
                        )
        );
                Paragraph Valor3= new Paragraph(Total,
                FontFactory.getFont("arial",
                        12,
                        Font.PLAIN,
                        BaseColor.BLACK
                        )
        );

        // Añadimos el titulo al documento
        documento.add(titulo);
        documento.add(cabeza);
        documento.add(cabeza2);
        documento.add(cabeza3);
        // Creamos una tabla
        PdfPTable tabla = new PdfPTable(3);
        tabla.addCell("Moto");
        tabla.addCell("Color");
        tabla.addCell("Cantidad");
        
        tabla.addCell(moto);
        tabla.addCell(color);
        tabla.addCell(Cantidad);
        
                // Añadimos la tabla al documento
        documento.add(tabla);
        
        documento.add(Pie);
        documento.add(Valor);
        documento.add(Pie2);
        documento.add(Valor2);
        documento.add(Pie3);
        documento.add(Valor3);
        //LLENAR TABLA CON FOR SI LOS DATOS ESTAN EN UNA LISTA
       /*for(int i = 0 ; i < lista.size() ; i++) {
            tabla.addCell(lista.get(i).getID());
            tabla.addCell(lista.get(i).getNombre());
            tabla.addCell(lista.get(i).getTelefono());
        }*/
        

        
        // Se cierra el documento
        documento.close();
        try {
Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"Proforma.pdf");
System.out.println("PDF Abriendo...");
} catch (IOException e) {
// TODO Auto-generated catch block
e.printStackTrace();
}
        }catch(Exception e)
        {
            System.err.println("Ocurrio un error al crear el archivo");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> ComboBoxConcesionario;
    public javax.swing.JList<String> ListaMotos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLIVA;
    private javax.swing.JLabel jLSubtotal;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblErrorLetra;
    private javax.swing.JLabel lblErrorLetra2;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtColor;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
