/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Controlador.ConcesionarioDAO;
import Controlador.Conexion;
import Controlador.MotoDAO;
import Controlador.PedidoDAO;
import Controlador.PedidoDetalleDADO;
import Controlador.ProformaDAO;
import Controlador.ProformaDetalleDAO;
import Modelo.Concesionario;
import Modelo.Detalle_Proforma;
import Modelo.Moto;
import Modelo.Pedido;
import Modelo.Proforma;
import Modelo.detalle_Pedido;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RojeruSan
 */
public class pnlReportes extends javax.swing.JPanel {

    Pedido ped=new Pedido();
    detalle_Pedido detped=new detalle_Pedido();
    PedidoDAO peddao=new PedidoDAO();
    PedidoDetalleDADO detpeddao=new PedidoDetalleDADO();
    Detalle_Proforma detpro=new Detalle_Proforma();
    ProformaDetalleDAO detprodao=new ProformaDetalleDAO();
    Proforma pro=new Proforma();
    ProformaDAO prodao=new ProformaDAO();
    Concesionario conc=new Concesionario();
    ConcesionarioDAO concdao=new ConcesionarioDAO();
    Moto moto=new Moto();
    MotoDAO motodao= new MotoDAO();
    public pnlReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMotos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tipoReporte = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        txtFecha = new com.toedter.calendar.JDateChooser();

        jButton7.setText("Buscar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 86, 186));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("EJEMPLO DE MENU HECHO EN JAVA");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/ios.png"))); // NOI18N
        jLabel7.setText("REPORTES");

        tblMotos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido", "Direccion"
            }
        ));
        jScrollPane2.setViewportView(tblMotos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Tipo reporte");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Fecha de incio");

        tipoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ventas", "Pedidos", "Facturas", "Proformas", "Motos", "Concesionarios" }));

        jButton8.setText("Buscar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tipoReporte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //SELECT * FROM `proforma` WHERE fecha_recepcion> DATE_FORMAT('1990/1/13',"%Y-%m-%d 00:00:00")
        
        try
        {
            if(tipoReporte.getSelectedItem()=="Ventas")
        {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            String Fecha = sdf.format(txtFecha.getDate());
            mostrarDatosVentas(Fecha);
        }
        if(tipoReporte.getSelectedItem()=="Pedidos")
        {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            String Fecha = sdf.format(txtFecha.getDate());
            mostrarDatosPedidos(Fecha);
        }
        if(tipoReporte.getSelectedItem()=="Facturas")
        {
            
        }
        if(tipoReporte.getSelectedItem()=="Proformas")
        {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            String Fecha = sdf.format(txtFecha.getDate());
            mostrarDatosProforma(Fecha);
            
        }
        if(tipoReporte.getSelectedItem()=="Motos")
        {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            String Fecha = sdf.format(txtFecha.getDate());
            mostrarDatosMotos("");
            
        }
        if(tipoReporte.getSelectedItem()=="Concesionarios")
        {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            String Fecha = sdf.format(txtFecha.getDate());
            mostrarDatosConcesionario("");
            
        }
        
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error Fecha " );
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    void mostrarDatosMotos(String valor){
        Conexion con = new Conexion();       
        String sql="";   
        DefaultTableModel modelo1 = new DefaultTableModel();
        modelo1.addColumn("Id Motocicleta");
        modelo1.addColumn("Modelo");
        modelo1.addColumn("Chasis");
        tblMotos.setModel(modelo1);
        valor="";
        if (valor.equals(""))
        {
            sql="SELECT * FROM moto";
        }
        else{
            sql="SELECT * FROM moto WHERE (id_moto='" + valor + "')";
        }          
        String []datos = new String[8];
        try{
            Statement st = con.getConnection().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                modelo1.addRow(datos);
            }
            //jfmotoadmin.tblMotos.setModel(modelo1);
        }catch(SQLException e){
            System.out.println(e);
        }
    }
    
    void mostrarDatosConcesionario(String valor){
        Conexion con = new Conexion();       
        String sql="";   
        DefaultTableModel modelo1 = new DefaultTableModel();
        modelo1.addColumn("Id Concesionario");
        modelo1.addColumn("Nombre");
        modelo1.addColumn("Direccion");
        modelo1.addColumn("Telefono");
        tblMotos.setModel(modelo1);
        valor="";
        if (valor.equals(""))
        {
            sql="SELECT * FROM concesionario";
        }
        else{
            sql="SELECT * FROM concesionario WHERE (id_concesionario='" + valor + "')";
        }          
        String []datos = new String[8];
        try{
            Statement st = con.getConnection().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                modelo1.addRow(datos);
            }
            //jfmotoadmin.tblMotos.setModel(modelo1);
        }catch(SQLException e){
            System.out.println(e);
        }
    }
    
    void mostrarDatosProforma(String valor){
        //JOptionPane.showMessageDialog(null, ComboBoxConcesionario.getSelectedItem());
        Conexion con = new Conexion();       
        String sql="";   
        DefaultTableModel modelo1 = new DefaultTableModel();
        modelo1.addColumn("Id Proforma");
        modelo1.addColumn("Fecha recepcion");
        modelo1.addColumn("Estado");
        modelo1.addColumn("Id Concesionario");
        modelo1.addColumn("Id Moto");
        modelo1.addColumn("Id Cantidad");
        modelo1.addColumn("Id Color");
        tblMotos.setModel(modelo1);
        if (valor.equals(""))
        {
            sql="SELECT proforma.id_proforma,proforma.fecha_recepcion,proforma.estado,proforma.id_concesionario,detalle_proforma.id_moto,detalle_proforma.cantidad,detalle_proforma.color FROM `proforma`,`detalle_proforma` WHERE proforma.id_proforma=detalle_proforma.id_proforma";
            //sql="SELECT * FROM proforma";
        }
        else{
            sql="SELECT proforma.id_proforma,proforma.fecha_recepcion,proforma.estado,proforma.id_concesionario,detalle_proforma.id_moto,detalle_proforma.cantidad,detalle_proforma.color FROM `proforma`,`detalle_proforma` WHERE proforma.id_proforma=detalle_proforma.id_proforma and proforma.fecha_recepcion>= DATE_FORMAT('"+valor+"',\"%Y-%m-%d 00:00:00\")";
            //sql="SELECT * FROM proforma WHERE (id_proforma='" + valor + "')";
        }          
        String []datos = new String[8];
        try{
            Statement st = con.getConnection().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                modelo1.addRow(datos);
            }
            //jfmotoadmin.tblMotos.setModel(modelo1);
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
void mostrarDatosPedidos(String valor){
        //JOptionPane.showMessageDialog(null, ComboBoxConcesionario.getSelectedItem());
        Conexion con = new Conexion();       
        String sql="";   
        DefaultTableModel modelo1 = new DefaultTableModel();
        modelo1.addColumn("Id Pedido");
        modelo1.addColumn("Fecha recepcion");
        modelo1.addColumn("Estado");
        modelo1.addColumn("Id Concesionario");
        modelo1.addColumn("Id Moto");
        modelo1.addColumn("Id Cantidad");
        modelo1.addColumn("Id Color");
        tblMotos.setModel(modelo1);
        if (valor.equals(""))
        {
            sql="SELECT pedido.cod_pedido,pedido.fecha_recepcion,pedido.estado,pedido.id_concesionario,detalle_pedido.id_moto,detalle_pedido.cantidad,detalle_pedido.color FROM `pedido`,`detalle_pedido` WHERE detalle_pedido.cod_pedido=pedido.cod_pedido";
            //sql="SELECT * FROM proforma";
        }
        else{
            sql="SELECT pedido.cod_pedido,pedido.fecha_recepcion,pedido.estado,pedido.id_concesionario,detalle_pedido.id_moto,detalle_pedido.cantidad,detalle_pedido.color FROM `pedido`,`detalle_pedido` WHERE detalle_pedido.cod_pedido=pedido.cod_pedido and pedido.fecha_recepcion>=DATE_FORMAT('"+valor+"',\"%Y-%m-%d 00:00:00\")";
            //sql="SELECT * FROM proforma WHERE (id_proforma='" + valor + "')";
        }          
        String []datos = new String[8];
        try{
            Statement st = con.getConnection().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                modelo1.addRow(datos);
            }
            //jfmotoadmin.tblMotos.setModel(modelo1);
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
void mostrarDatosVentas(String valor){
        //JOptionPane.showMessageDialog(null, ComboBoxConcesionario.getSelectedItem());
        Conexion con = new Conexion();       
        String sql="";   
        DefaultTableModel modelo1 = new DefaultTableModel();
        modelo1.addColumn("Id Venta");
        modelo1.addColumn("Usuario");
        modelo1.addColumn("Fecha");
        modelo1.addColumn("Estado");
        modelo1.addColumn("Pedido");
        modelo1.addColumn("Factura");
        tblMotos.setModel(modelo1);
        if (valor.equals(""))
        {
            sql="SELECT * FROM `venta`";
            //sql="SELECT * FROM proforma";
        }
        else{
            sql="SELECT * FROM `venta` WHERE venta.fecha>=DATE_FORMAT('"+valor+"',\"%Y-%m-%d 00:00:00\")";
            //sql="SELECT * FROM proforma WHERE (id_proforma='" + valor + "')";
        }          
        String []datos = new String[8];
        try{
            Statement st = con.getConnection().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                modelo1.addRow(datos);
            }
            //jfmotoadmin.tblMotos.setModel(modelo1);
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }

public static Date ParseFecha(String fecha)
    {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
        Date fechaDate = null;
        try {
            fechaDate = formato.parse(fecha);
        } 
        catch (Exception ex) 
        {
            System.out.println(ex);
        }
        return fechaDate;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tblMotos;
    public javax.swing.JComboBox<String> tipoReporte;
    private com.toedter.calendar.JDateChooser txtFecha;
    // End of variables declaration//GEN-END:variables
}
